"""
Knowledge models for document storage and vector embeddings.

This module defines models for storing ingested documents and their
vector embeddings for semantic search using pgvector.
"""
from datetime import datetime
from typing import List, Optional
import enum

from sqlalchemy import (
    BigInteger, Integer, String, Text, TIMESTAMP, Boolean, ForeignKey,
    Enum as SQLEnum, Float, func
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, TimestampMixin
from .types import TSVECTOR, Vector, JSONB


class ContentType(str, enum.Enum):
    """Enumeration of content types for knowledge documents."""
    PAGE = "page"
    ISSUE = "issue"
    DOCUMENT = "document"
    VIDEO_TRANSCRIPT = "video_transcript"


class KnowledgeDocument(Base, TimestampMixin):
    """
    Knowledge document model for storing ingested content.

    Represents documents ingested from various data sources like Confluence pages,
    JIRA issues, and other knowledge repositories.

    Attributes:
        id: Primary key
        data_source_id: Foreign key to data_sources table
        external_id: ID in the external system
        title: Document title
        content: Full text content
        content_type: Type of content (page, issue, document, video_transcript)
        url: URL to the original document
        metadata: Additional metadata (JSON)
        document_hash: Hash for deduplication
        indexed_at: When the document was indexed
        updated_at: When the document was last updated
        is_deleted: Soft delete flag
        tsvector_content: Full-text search vector (auto-generated by trigger)
        video_start_time: Video timestamp start (seconds) for transcript chunks
        video_end_time: Video timestamp end (seconds) for transcript chunks
        video_duration: Total video duration in seconds

    Relationships:
        data_source: Associated data source
        embeddings: List of vector embeddings for this document
    """
    __tablename__ = "knowledge_documents"

    # Primary key
    id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
        comment="Unique document identifier"
    )

    # Foreign keys
    data_source_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("data_sources.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Associated data source ID"
    )

    # Document attributes
    external_id: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        comment="ID in the external system"
    )

    title: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Document title"
    )

    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Full text content"
    )

    content_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Type of content"
    )

    url: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="URL to the original document"
    )

    doc_metadata: Mapped[Optional[dict]] = mapped_column(
        "metadata",  # Database column name
        JSONB,
        nullable=True,
        comment="Additional metadata (author, tags, etc.)"
    )

    document_hash: Mapped[Optional[str]] = mapped_column(
        String(64),
        nullable=True,
        index=True,
        comment="SHA-256 hash for deduplication"
    )

    indexed_at: Mapped[datetime] = mapped_column(
        TIMESTAMP,
        nullable=False,
        server_default=func.now(),
        comment="When the document was indexed"
    )

    # Note: updated_at from TimestampMixin

    is_deleted: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default="false",
        default=False,
        comment="Soft delete flag"
    )

    # Full-text search vector (auto-generated by database trigger)
    tsvector_content: Mapped[Optional[str]] = mapped_column(
        TSVECTOR,
        nullable=True,
        comment="Full-text search vector (auto-generated)"
    )

    # Video metadata (for video transcripts)
    video_start_time: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="Video timestamp start in seconds (for video transcript chunks)"
    )

    video_end_time: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="Video timestamp end in seconds (for video transcript chunks)"
    )

    video_duration: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
        comment="Total video duration in seconds"
    )

    # Relationships
    data_source: Mapped["DataSource"] = relationship(
        "DataSource",
        back_populates="knowledge_documents",
        lazy="selectin"
    )

    embeddings: Mapped[List["DocumentEmbedding"]] = relationship(
        "DocumentEmbedding",
        back_populates="document",
        cascade="all, delete-orphan",
        order_by="DocumentEmbedding.chunk_index",
        lazy="selectin"
    )

    def __repr__(self) -> str:
        """String representation of the KnowledgeDocument model."""
        title_preview = self.title[:50] + "..." if len(self.title) > 50 else self.title
        return f"<KnowledgeDocument(id={self.id}, title='{title_preview}')>"


class DocumentEmbedding(Base):
    """
    Document embedding model for vector-based semantic search.

    Stores vector embeddings for document chunks using pgvector for
    efficient similarity search.

    Attributes:
        id: Primary key
        document_id: Foreign key to knowledge_documents table
        chunk_index: Index of the chunk within the document
        chunk_text: Text content of the chunk
        embedding: Vector embedding (pgvector type)
        token_count: Number of tokens in the chunk
        created_at: Creation timestamp

    Relationships:
        document: Associated knowledge document
    """
    __tablename__ = "document_embeddings"

    # Primary key
    id: Mapped[int] = mapped_column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
        comment="Unique embedding identifier"
    )

    # Foreign keys
    document_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("knowledge_documents.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Associated document ID"
    )

    # Embedding attributes
    chunk_index: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        comment="Index of the chunk within the document"
    )

    chunk_text: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Text content of the chunk"
    )

    # pgvector column for embeddings (768 dimensions for Ollama nomic-embed-text)
    embedding: Mapped[Vector] = mapped_column(
        Vector(768),
        nullable=False,
        comment="Vector embedding (768 dimensions)"
    )

    token_count: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="Number of tokens in the chunk"
    )

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP,
        nullable=False,
        server_default=func.now(),
        comment="Creation timestamp"
    )

    # Relationships
    document: Mapped["KnowledgeDocument"] = relationship(
        "KnowledgeDocument",
        back_populates="embeddings",
        lazy="selectin"
    )

    def __repr__(self) -> str:
        """String representation of the DocumentEmbedding model."""
        text_preview = self.chunk_text[:50] + "..." if len(self.chunk_text) > 50 else self.chunk_text
        return (
            f"<DocumentEmbedding(id={self.id}, document_id={self.document_id}, "
            f"chunk_index={self.chunk_index}, text='{text_preview}')>"
        )
