"""add_missing_tables

Revision ID: e5faa0c897a2
Revises: 002
Create Date: 2026-06-20 17:20:39.311126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5faa0c897a2'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (unique)"),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password for authentication'),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='user_role', create_constraint=True), server_default='user', nullable=False, comment='User role (admin or user)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Flag indicating if the user account is active'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique audit log identifier'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User who performed the action'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Description of the action performed'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='Type of resource affected'),
    sa.Column('resource_id', sa.BigInteger(), nullable=True, comment='ID of the affected resource'),
    sa.Column('changes', src.models.types.JSONB(), nullable=True, comment='JSON object containing the changes made'),
    sa.Column('ip_address', src.models.types.INET(), nullable=True, comment='IP address of the user'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the action occurred'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', src.models.types.UUID(length=36), nullable=False, comment='Unique session identifier (UUID)'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Associated user ID (null for anonymous users)'),
    sa.Column('session_token', sa.String(length=255), nullable=False, comment='Unique session token'),
    sa.Column('ip_address', src.models.types.INET(), nullable=True, comment='IP address of the user'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='Browser user agent string'),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Session start timestamp'),
    sa.Column('last_activity_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Last activity timestamp'),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True, comment='Session end timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_session_token'), 'chat_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique data source identifier'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name of the data source'),
    sa.Column('type', sa.Enum('CONFLUENCE', 'JIRA', 'ONBOARDING', 'FOLDER_WATCH', 'CUSTOM', name='data_source_type', create_constraint=True), nullable=False, comment='Type of data source'),
    sa.Column('config', src.models.types.JSONB(), nullable=True, comment='Configuration settings (URLs, credentials, filters)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Flag indicating if the data source is active'),
    sa.Column('sync_schedule', sa.String(length=50), nullable=True, comment='Cron expression for sync scheduling'),
    sa.Column('last_sync_at', sa.TIMESTAMP(), nullable=True, comment='Timestamp of last successful sync'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this data source'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_created_by'), 'data_sources', ['created_by'], unique=False)
    op.create_index(op.f('ix_data_sources_type'), 'data_sources', ['type'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique message identifier'),
    sa.Column('session_id', src.models.types.UUID(length=36), nullable=False, comment='Associated chat session ID'),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='message_role', create_constraint=True), nullable=False, comment='Message role (user, assistant, or system)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Message text content'),
    sa.Column('metadata', src.models.types.JSONB(), nullable=True, comment='Additional metadata (sources, tokens, etc.)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Message creation timestamp'),
    sa.Column('embedding', sa.JSON(), nullable=True, comment='Optional embedding vector for semantic search (stored as JSON array)'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique ingestion job identifier'),
    sa.Column('data_source_id', sa.Integer(), nullable=False, comment='Associated data source ID'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='job_status', create_constraint=True), nullable=False, comment='Current job status'),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True, comment='Job start timestamp'),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True, comment='Job completion timestamp'),
    sa.Column('documents_processed', sa.Integer(), server_default='0', nullable=False, comment='Number of documents successfully processed'),
    sa.Column('documents_failed', sa.Integer(), server_default='0', nullable=False, comment='Number of documents that failed processing'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if job failed'),
    sa.Column('metadata', src.models.types.JSONB(), nullable=True, comment='Additional metadata (logs, stats, etc.)'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_data_source_id'), 'ingestion_jobs', ['data_source_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique document identifier'),
    sa.Column('data_source_id', sa.Integer(), nullable=False, comment='Associated data source ID'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='ID in the external system'),
    sa.Column('title', sa.Text(), nullable=False, comment='Document title'),
    sa.Column('content', sa.Text(), nullable=False, comment='Full text content'),
    sa.Column('content_type', sa.Enum('PAGE', 'ISSUE', 'DOCUMENT', 'VIDEO_TRANSCRIPT', name='content_type', create_constraint=True), nullable=False, comment='Type of content'),
    sa.Column('url', sa.Text(), nullable=True, comment='URL to the original document'),
    sa.Column('metadata', src.models.types.JSONB(), nullable=True, comment='Additional metadata (author, tags, etc.)'),
    sa.Column('document_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash for deduplication'),
    sa.Column('indexed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='When the document was indexed'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft delete flag'),
    sa.Column('tsvector_content', src.models.types.TSVECTOR(), nullable=True, comment='Full-text search vector (auto-generated)'),
    sa.Column('video_start_time', sa.Float(), nullable=True, comment='Video timestamp start in seconds (for video transcript chunks)'),
    sa.Column('video_end_time', sa.Float(), nullable=True, comment='Video timestamp end in seconds (for video transcript chunks)'),
    sa.Column('video_duration', sa.Float(), nullable=True, comment='Total video duration in seconds'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the record was last updated'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_data_source_id'), 'knowledge_documents', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_document_hash'), 'knowledge_documents', ['document_hash'], unique=False)
    op.create_table('document_embeddings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Unique embedding identifier'),
    sa.Column('document_id', sa.BigInteger(), nullable=False, comment='Associated document ID'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Index of the chunk within the document'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='Text content of the chunk'),
    sa.Column('embedding', src.models.types.Vector(), nullable=False, comment='Vector embedding (1536 dimensions)'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Number of tokens in the chunk'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_index(op.f('ix_knowledge_documents_document_hash'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_data_source_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_ingestion_jobs_data_source_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_data_sources_type'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_created_by'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_session_token'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
